### PR TITLE
Hillslope2d

### PR DESCRIPTION
**Pull request by arijitlaik**
Hi @rbeucher have added basic hillslope diffusion for 2d model, its a WIP, especially for large dt and low diffusivities a filter need to be used to stop the FCT from oscillating. Merge it if you wish, comment and review

### CODE REVIEW

**Comment by rbeucher** [comment]
have you tested this in parallel? Would be good to have a test, a model?

**Comment by rbeucher** [comment]
I doubt this will work in parallel as there is no guarantee that the order of the particles will be maintained in memory.. that's why i have been working on global index and I haven't finished yet.

**Comment by arijitlaik** [comment]
Yes, have run this on mpi with 2 threads, works, will email the file?

**Comment by arijitlaik** [comment]
I am closing this. I guess a better implementation should be done, especially by tracking surface swarms and then doing any modification to that surface interface and or a better coupling with quagmire or PyBadlands. But using those in 2d might just be an over kill.

**Pull request closed without merging**
