### PR TITLE
Make solver object part of the model class

### PR DESCRIPTION
**Pull request by LukeMondy**
As a fix for issue: https://github.com/rbeucher/UWGeodynamics/issues/62

### CODE REVIEW

**Comment by rbeucher** [comment]
No that won't work. A new solver is built each time we call the solve method and I would like to keep that.

**Comment by rbeucher** [comment]
As a temporary fix you can overload the Model.stokes_solver function directly in your script.
you build a solver using UW and then do

```python
def function():
    #build your solver here

Model.stokes_solver = function

```
That should work...(I have not tried...)

**Comment by rbeucher** [comment]
I agree we need to enable this. It's not just the solver options... all the petsc options should also be available.

**Comment by rbeucher** [comment]
Actually my bad.. Your solution is equivalent to mine. You end up with a static solver.

**Comment by OlympusMonds** [comment]
I could add a flag for `self.static_solver = false` or to the `stokes_solver` method, and then allow the user to enable it if they want?

**Comment by LukeMondy** [comment]
I could add a flag to the model object (`self.static_solver = false`) or to the method `stokes_solver` to allow the user to choose?

**Comment by rbeucher** [comment]
Yes do that for now. Sounds good.

**Comment by LukeMondy** [comment]
OK, I made the changes. Let me know what you think.

**Comment by rbeucher** [comment]
what about doing:

```python
self._static_solver = False # in the init method

@property
def solver(self):
    return self._solver

@solver.setter
def solver(self, value):
    self._static_solver = True
    self._solver = value

def stokes_solver(self):
    if not self._static_solver:
        ...
```

Then when we define Model.solver, we implicitely set the solver to be static.

**Comment by LukeMondy** [comment]
So then if I wanted a static solver in my model, I would have to do something like:
```
Model.solver = Model.stokes_solver()
Model.solver.options.scr.ksp_rtol = 1e-3
```
Is that right?

**Comment by rbeucher** [comment]
Yeah something like that. What was you initial idea?

**Comment by LukeMondy** [comment]
No, no initial idea, just making sure we're on the same page! I'll make the changes you recommend.

**Comment by rbeucher** [comment]
I think it is simpler like that. We can always change if it does not work

**Pull request merged**
