### PR TITLE
Rev visc fn exp

### PR DESCRIPTION
**Pull request by arijitlaik**
Such Redundant Code for just about 3 seconds ;/
```
%time Model._viscosityFn.evaluate(Model.swarm)
CPU times: user 39.2 s, sys: 404 ms, total: 39.6 s
Wall time: 39.7 s

%time Model._viscosityFn2.evaluate(Model.swarm)
CPU times: user 35 s, sys: 336 ms, total: 35.3 s
Wall time: 35.4 s
```

feel free to a purge this code, or rename the viscosityFn2 to ._viscosityFn,
and the self.getXeta2() where X∈ {Viscous, Elastic, Plastic, MeltModifyu}

### CODE REVIEW

**Comment by rbeucher** [comment]
reading your code I was expecting something like this....:/

**Comment by arijitlaik** [comment]
the master/dev branch takes 
```
%time Model._viscosityFn.evaluate(Model.swarm)
CPU times: user 15.1 s, sys: 112 ms, total: 15.2 s
Wall time: 15.2 s

```
hence the previous messy function is much better.

**Comment by rbeucher** [comment]
How many materials?

**Comment by arijitlaik** [comment]
6.
Sediment
Mantle
MantleLithosphere
UppperCrust
StickyAir
Air

**Comment by arijitlaik** [comment]
Closing this one. As it doesn't work. Something new for combining rheology maybe, that's both clean and fast

**Pull request closed without merging**
