### PR TITLE
Update Manual, provides information on solver options

### PR DESCRIPTION
**Pull request by arijitlaik**
Add solver options in the manual

### CODE REVIEW

**Comment by arijitlaik** [comment]
Would you consider merging this?

**Comment by rbeucher** [comment]
Not for now. I haven't played with the solvers yet. There are to many things untested for now.

**Comment by arijitlaik** [comment]
Can a basic test model be defined which tests for all the functionalities?

**Comment by arijitlaik** [comment]
Moreover, I have tested my models with lu and superlu but not super lu dist, so if you could provide and or define which example would be ideally considered a test model, i could try running those and report back the tests.

**Pull request merged**
